apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: zad2gitops
              image: patston/zad2gitops:latest
              command:
                - "/bin/sh"
                - "-ec"
              args:
                - git clone https://github.com/patston/ConfigRepo.git /tmp/repo && find /tmp/repo -name '*.yaml' -exec kubectl apply -f '{}' \;
